version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ${NODE_ENV:-development}.Dockerfile
    ports:
      - "${PORT:-8080}:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID:-n9u23251}
      - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET:-production}
      - SANITY_API_VERSION=${SANITY_API_VERSION:-2024-03-21}
      - WATCHPACK_POLLING=true
    restart: unless-stopped